# -*- coding: utf-8 -*-
login = "rebekka.pluess@ji.zh.ch"
password = "rm&zh"
linien_col  = ""
linien_doc  = ""
linien_TR  = ""
suchenErsetzenCol  = ""
suchenErsetzenDoc  = ""
exportCol = ""
exportDoc  = ""
importCol  = ""
sampleCol  = ""
sampleDoc  = ""
